//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalEvidenceBulkProcessor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranch
    {
        public int ID { get; set; }
        public int StateID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public bool Suspended { get; set; }
        public string LastXNo { get; set; }
        public bool OnlineRealTime { get; set; }
    }
}
