//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalEvidenceBulkProcessor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IZUUser
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string BranchCode { get; set; }
        public string UserNames { get; set; }
        public string Password { get; set; }
        public bool ResetPassword { get; set; }
        public bool CanRegister { get; set; }
        public bool CaptureImage { get; set; }
        public bool BrowseTransaction { get; set; }
        public bool Upload { get; set; }
        public bool SetupUser { get; set; }
        public bool SetupBranch { get; set; }
        public bool SetUpSystemParameters { get; set; }
        public bool SetUpTranscopeParameters { get; set; }
        public bool AddUser { get; set; }
        public bool EditUser { get; set; }
        public bool BrowseUser { get; set; }
        public bool DeleteUser { get; set; }
        public bool AddCountry { get; set; }
        public bool EditCountry { get; set; }
        public bool BrowseCountry { get; set; }
        public bool DeleteCountry { get; set; }
        public bool AddState { get; set; }
        public bool EditState { get; set; }
        public bool BrowseState { get; set; }
        public bool DeleteState { get; set; }
        public bool AddTransactionCategory { get; set; }
        public bool EditTransactionCategory { get; set; }
        public bool BrowseTransactionCategory { get; set; }
        public bool DeleteTransactionCategory { get; set; }
        public bool ViewReports { get; set; }
        public bool ExportTransaction { get; set; }
        public bool PrintTransaction { get; set; }
        public bool SuperUser { get; set; }
        public bool Suspended { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public bool CanConfigurePollData { get; set; }
        public bool CanConfigureDataMover { get; set; }
        public System.DateTime LastLogOn { get; set; }
    }
}
